@startuml

namespace random3dmaze {
  namespace ui {
    namespace infrastructure {
      interface presenter {
        on_create() : void
        on_foreground() : void
        on_background() : void
        on_destroy() : void

        on_create_view(context : graphics_context) : void
        on_draw(context : graphics_context) : void
        on_destroy_view(context : graphics_context) : void

        on_key_event(event : key_event) : void
      }

      namespace graphics {
        class graphics_context {
          set_color(color : color) : void
          clear() : void
          fill_rect(rect : rect) : void
        }

        class surface {
        }

        class color {
        }

        class rect {
        }

        graphics_context o-- surface
      }

      application o-- presenter
      application ..> graphics.graphics_context

      presenter ..> graphics.graphics_context
    }

    main_presenter ..|> infrastructure.presenter
    main_presenter o-- sight_view
    main_presenter o-- map_view
  }
}

@enduml
